name: one
services:
  db:
    image: citusdata/citus:latest
    container_name: citus-one
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ../.env
    volumes:
      - one_db_citus_data:/var/lib/postgresql/data
    networks:
      - app-one

  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - ${PORT_REDIS}:6379
    env_file:
      - ../.env
    networks:
      - app-one
    volumes:
      - one_redis_data:/bitnami/redis
    command: [ "redis-server", "--bind", "0.0.0.0", "--requirepass", "${REDIS_PASSWORD}", "--save", "" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 10
  # app:
  #   build:
  #     context: ./apps/one
  #     dockerfile: Dockerfile
  #   container_name: one_app
  #   env_file:
  #     - ../.env
  #   ports:
  #     - ${PORT_BACKEND}:${PORT_BACKEND}
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - app-one
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - ${PORT_PROMETHEUS}:9090
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - app-one
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - ${PORT_GRANAFA}:3000
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   networks:
  #     - app-one

volumes:
  one_db_citus_data:
    name: one_citus-data
  one_redis_data:
    name: one_redis-data

networks:
  app-one:
    driver: bridge
